
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int EXCLAMACION = 2;
  public static final int DOSPUNTOS = 3;
  public static final int TK_END = 13;
  public static final int TK_ENDPROGRAM = 14;
  public static final int MENORQ = 8;
  public static final int EOF = 0;
  public static final int FLECHAI = 4;
  public static final int PTYCOMA = 5;
  public static final int BLANCOS = 10;
  public static final int IGUAL = 7;
  public static final int error = 1;
  public static final int ENTEROS = 11;
  public static final int TK_PROGRAM = 12;
  public static final int MAYORQ = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMACION",
  "DOSPUNTOS",
  "FLECHAI",
  "PTYCOMA",
  "COMA",
  "IGUAL",
  "MENORQ",
  "MAYORQ",
  "BLANCOS",
  "ENTEROS",
  "TK_PROGRAM",
  "TK_END",
  "TK_ENDPROGRAM"
  };
}

